Feat/register form
mayst/bxchgr pull request #7
Opened 2023-07-08 22:36 UTC by kurilyov

2023-07-08 22:50 UTC, mayst requested changes
make validation for reg form. move it to page folder. make general components for textfield and btn

2023-07-14 18:26 UTC, mayst commented on src/components/FormInput.tsx
make a folder 'inputs' put this component there. rename it to 'TextFieldBx'

2023-07-14 18:36 UTC, kurilyov commented on src/components/FormInput.tsx
Done

2023-07-14 18:38 UTC, kurilyov commented
Done

2023-07-14 18:41 UTC, mayst approved these changes

2023-07-14 18:42 UTC, merged